61 create indexjson and csv from file structure
labdao/ganglia pull request #66
Opened 2023-02-06 20:50 UTC by NiklasTR

2023-02-06 20:52 UTC, NiklasTR commented
run the command from within the repo:

go run utils.go --application="diffdock" --input_directory="path/to/sdf-and-pdb"

2023-02-07 10:24 UTC, thetechnocrat-dev requested changes
It worked for me locally 💪 

There was a fair amount of scope creep in the PR around introducing a CLI and adding the concept of app config JSONL. Totally understand why that naturally emerged. Let's spend some engineering meeting time discussing a merge strategy.

Other smaller things
* remove dead code comments
* run `go fmt`
* break up large functions where possible
* less noise in code comments
* add unit tests (don't need 100% coverage but at least a few)
* I found the function names at the start of the utils file intuitive and then started to get confused by the function names towards the end of the file
* there are a lot of TODO comments

2023-02-07 15:34 UTC, NiklasTR commented on plexus/utils.go
> +// validate that the directory path exists and is a directory
thank you - will make changes

2023-02-07 21:52 UTC, NiklasTR commented on plexus/utils.go
> +func indexCreateIndexJSONL(new_files []string, app_config *string, volume_path string) (string, []map[string]string) {
I broke it into three functions and renamed it

2023-02-07 21:53 UTC, NiklasTR commented on plexus/utils.go
> +func indexCreateInputsVolume(volume_directory *string, files []string, prefix string) (string, []string, string) {
resolved

2023-02-07 21:55 UTC, NiklasTR commented
should be ready for sign-off generally. I will add tests tomorrow in the AM.

2023-02-08 14:11 UTC, thetechnocrat-dev approved these changes
🥇 LGTM

2023-02-08 17:15 UTC, acashmoney approved these changes
LGTM

2023-02-08 17:15 UTC, merged